### PR TITLE
Added updatemytalks_as private handler and sub ajax_stateful_handler

### PR DESCRIPTION
**Pull request by nugged**
Added 'updatemytalks_as' for ajax_stateful_handler to specifically set or clean user's
favorite task, not to toggle.

On some pages of YAPC::EU::2015 there is few 'favorite' buttons for same task,
and when they both off and visitor presses them one-by-one, they both become
toggled to 'on' state, but two in a row request to old updatemytalks_a handler
toggles task in favorites from off to on and back to off.

So we need separate handler:
- updatemytalks_a -> toggles by 'task_id' in request.
- updatemytalks_as -> sets 'task_id' favorite state depending from additional 'state' parameter

For latter one we already provide preparations in javascript already, there:
https://github.com/Act-Conferences/ye2015/blob/master/wwwdocs/js/main.js#L22-L26

### CODE REVIEW

**Comment by nugged** [comment]
@alexm: already sent pull request to main repo: https://github.com/book/Act/pull/62
but in case you need your, more local, in separate branch -- here is it.

**Comment by alexm** [comment]
I'm only using this fork to contribute changes to upstream, but thanks anyway.

**Comment by nugged** [comment]
> I'm only using this fork to contribute changes to upstream, but thanks anyway.

I created p.r. also in main repo, but I thought, what if this one you use to current ye2015.

Anyway, in description I tried to give detailed explanation, why 'toggable' ajax handler not good for us, so why I need another one handle. If we will get this into current running yapc server (production?) then I can change that ye2015 repo to use this updatemytalks_as handler.

**Comment by alexm** [comment]
All Act instances run on the same server sharing the same code base, only the `wwwdocs` and `actdocs` are specific of each instance and managed by their respective organizers through a code repository (ye2015 in our case).

I'm afraid that the only way to change the shared code base is by sending a PR to [book/Act](https://github.com/book/Act) and have it accepted.

**Comment by nugged** [comment]
Yes, I've send: https://github.com/book/Act/pull/62
in same time with yours. How to make it accepted?

**Pull request closed without merging**
